apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1
  labels:
    app: my-app1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: my-app1
        image: pradiptakayal/project-2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080        
        readinessProbe:
          httpGet:
            path: /webapp
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 30
      terminationGracePeriodSeconds: 30            
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app1
spec:
  type: NodePort
  selector:
    app: my-app1
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000
