apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-core-app
  labels:
    app: dotnet-core-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dotnet-core-app
  template:
    metadata:
      labels:
        app: dotnet-core-app
    spec:
      containers:
      - name: coreapp
        image: pradiptakayal/project-2:latest  # Replace with your Docker image
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-core-service
spec:
  type: NodePort
  selector:
    app: dotnet-core-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Choose an appropriate port within the range 30000-32767
